/* DO NOT EDIT THIS FILE - it is machine generated */
#include </usr/jdk1.8.0_181/include/jni.h>
/* Header for class TestJNI */

#ifndef _Included_TestJNI
#define _Included_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNI
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TestJNI_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
